### ISSUE TITLE
Issue-Initial Redux Setup

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#101]
Automated Review Comments
Issues in package-lock.json:
  - (4, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (56, 'Line exceeds 80 characters')
  - (56, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (65, 'Line exceeds 80 characters')
  - (65, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (66, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (71, 'Line exceeds 80 characters')
  - (71, 'Hardcoded string found')
  - (72, 'Line exceeds 80 characters')
  - (72, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (97, 'Hardcoded string found')
  - (98, 'Line exceeds 80 characters')
  - (98, 'Hardcoded string found')
  - (99, 'Line exceeds 80 characters')
  - (99, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (107, 'Line exceeds 80 characters')
  - (107, 'Hardcoded string found')
  - (108, 'Line exceeds 80 characters')
  - (108, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (116, 'Line exceeds 80 characters')
  - (116, 'Hardcoded string found')
  - (117, 'Line exceeds 80 characters')
  - (117, 'Hardcoded string found')
  - (118, 'Line exceeds 80 characters')
  - (118, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (125, 'Line exceeds 80 characters')
  - (125, 'Hardcoded string found')
  - (126, 'Line exceeds 80 characters')
  - (126, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (128, 'Hardcoded string found')
  - (133, 'Hardcoded string found')
  - (134, 'Line exceeds 80 characters')
  - (134, 'Hardcoded string found')
  - (135, 'Line exceeds 80 characters')
  - (135, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (142, 'Hardcoded string found')
  - (143, 'Line exceeds 80 characters')
  - (143, 'Hardcoded string found')
  - (144, 'Line exceeds 80 characters')
  - (144, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (150, 'Hardcoded string found')
  - (151, 'Hardcoded string found')
  - (152, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (154, 'Line exceeds 80 characters')
  - (154, 'Hardcoded string found')
  - (155, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
  - (160, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (163, 'Line exceeds 80 characters')
  - (163, 'Hardcoded string found')
  - (166, 'Hardcoded string found')
  - (167, 'Line exceeds 80 characters')
  - (167, 'Hardcoded string found')
  - (168, 'Line exceeds 80 characters')
  - (168, 'Hardcoded string found')
  - (169, 'Hardcoded string found')
  - (174, 'Hardcoded string found')
  - (175, 'Line exceeds 80 characters')
  - (175, 'Hardcoded string found')
  - (179, 'Hardcoded string found')
  - (180, 'Line exceeds 80 characters')
  - (180, 'Hardcoded string found')
  - (181, 'Line exceeds 80 characters')
  - (181, 'Hardcoded string found')
  - (182, 'Hardcoded string found')
  - (183, 'Hardcoded string found')
  - (184, 'Hardcoded string found')
  - (188, 'Hardcoded string found')
  - (189, 'Line exceeds 80 characters')
  - (189, 'Hardcoded string found')
  - (190, 'Line exceeds 80 characters')
  - (190, 'Hardcoded string found')
  - (191, 'Hardcoded string found')
  - (192, 'Hardcoded string found')
  - (197, 'Hardcoded string found')
  - (198, 'Line exceeds 80 characters')
  - (198, 'Hardcoded string found')
  - (199, 'Line exceeds 80 characters')
  - (199, 'Hardcoded string found')
  - (200, 'Hardcoded string found')
  - (201, 'Hardcoded string found')
  - (202, 'Hardcoded string found')
  - (206, 'Hardcoded string found')
  - (207, 'Line exceeds 80 characters')
  - (207, 'Hardcoded string found')
  - (208, 'Line exceeds 80 characters')
  - (208, 'Hardcoded string found')
  - (209, 'Line exceeds 80 characters')
  - (209, 'Hardcoded string found')
  - (210, 'Hardcoded string found')
  - (215, 'Hardcoded string found')
  - (216, 'Line exceeds 80 characters')
  - (216, 'Hardcoded string found')
  - (217, 'Line exceeds 80 characters')
  - (217, 'Hardcoded string found')
  - (218, 'Hardcoded string found')
  - (219, 'Hardcoded string found')
  - (224, 'Hardcoded string found')
  - (225, 'Line exceeds 80 characters')
  - (225, 'Hardcoded string found')
  - (226, 'Line exceeds 80 characters')
  - (226, 'Hardcoded string found')
  - (227, 'Hardcoded string found')
  - (228, 'Hardcoded string found')
  - (233, 'Hardcoded string found')
  - (234, 'Line exceeds 80 characters')
  - (234, 'Hardcoded string found')
  - (235, 'Line exceeds 80 characters')
  - (235, 'Hardcoded string found')
  - (236, 'Hardcoded string found')
  - (237, 'Hardcoded string found')
  - (242, 'Hardcoded string found')
  - (243, 'Line exceeds 80 characters')
  - (243, 'Hardcoded string found')
  - (244, 'Line exceeds 80 characters')
  - (244, 'Hardcoded string found')
  - (245, 'Hardcoded string found')
  - (246, 'Hardcoded string found')
  - (251, 'Hardcoded string found')
  - (252, 'Line exceeds 80 characters')
  - (252, 'Hardcoded string found')
  - (253, 'Line exceeds 80 characters')
  - (253, 'Hardcoded string found')
  - (254, 'Hardcoded string found')
  - (260, 'Hardcoded string found')
  - (261, 'Hardcoded string found')
  - (262, 'Hardcoded string found')
  - (263, 'Hardcoded string found')
  - (269, 'Hardcoded string found')
  - (270, 'Hardcoded string found')
  - (271, 'Hardcoded string found')
  - (272, 'Hardcoded string found')
  - (274, 'Hardcoded string found')
  - (278, 'Hardcoded string found')
  - (279, 'Line exceeds 80 characters')
  - (279, 'Hardcoded string found')
  - (280, 'Line exceeds 80 characters')
  - (280, 'Hardcoded string found')
  - (281, 'Line exceeds 80 characters')
  - (281, 'Hardcoded string found')
  - (287, 'Hardcoded string found')
  - (288, 'Hardcoded string found')
  - (289, 'Hardcoded string found')
  - (290, 'Hardcoded string found')
  - (292, 'Hardcoded string found')
  - (296, 'Hardcoded string found')
  - (297, 'Line exceeds 80 characters')
  - (297, 'Hardcoded string found')
  - (298, 'Line exceeds 80 characters')
  - (298, 'Hardcoded string found')
  - (299, 'Hardcoded string found')
  - (300, 'Hardcoded string found')
  - (303, 'Hardcoded string found')
  - (305, 'Hardcoded string found')
  - (306, 'Hardcoded string found')
  - (307, 'Hardcoded string found')
  - (308, 'Line exceeds 80 characters')
  - (308, 'Hardcoded string found')
  - (309, 'Hardcoded string found')
  - (310, 'Hardcoded string found')
  - (314, 'Hardcoded string found')
  - (315, 'Line exceeds 80 characters')
  - (315, 'Hardcoded string found')
  - (316, 'Line exceeds 80 characters')
  - (316, 'Hardcoded string found')
  - (317, 'Hardcoded string found')
  - (319, 'Hardcoded string found')
  - (323, 'Hardcoded string found')
  - (324, 'Line exceeds 80 characters')
  - (324, 'Hardcoded string found')
  - (325, 'Line exceeds 80 characters')
  - (325, 'Hardcoded string found')
  - (326, 'Hardcoded string found')
  - (328, 'Hardcoded string found')
  - (330, 'Hardcoded string found')
  - (331, 'Hardcoded string found')
  - (332, 'Hardcoded string found')
  - (333, 'Line exceeds 80 characters')
  - (333, 'Hardcoded string found')
  - (334, 'Line exceeds 80 characters')
  - (334, 'Hardcoded string found')
  - (335, 'Hardcoded string found')
  - (337, 'Hardcoded string found')
  - (341, 'Hardcoded string found')
  - (342, 'Line exceeds 80 characters')
  - (342, 'Hardcoded string found')
  - (343, 'Line exceeds 80 characters')
  - (343, 'Hardcoded string found')
  - (344, 'Hardcoded string found')
  - (350, 'Hardcoded string found')
  - (351, 'Line exceeds 80 characters')
  - (351, 'Hardcoded string found')
  - (352, 'Line exceeds 80 characters')
  - (352, 'Hardcoded string found')
  - (353, 'Line exceeds 80 characters')
  - (353, 'Hardcoded string found')
  - (354, 'Hardcoded string found')
  - (359, 'Hardcoded string found')
  - (360, 'Line exceeds 80 characters')
  - (360, 'Hardcoded string found')
  - (361, 'Line exceeds 80 characters')
  - (361, 'Hardcoded string found')
  - (362, 'Hardcoded string found')
  - (368, 'Hardcoded string found')
  - (369, 'Line exceeds 80 characters')
  - (369, 'Hardcoded string found')
  - (370, 'Line exceeds 80 characters')
  - (370, 'Hardcoded string found')
  - (371, 'Hardcoded string found')
  - (377, 'Hardcoded string found')
  - (378, 'Hardcoded string found')
  - (379, 'Hardcoded string found')
  - (380, 'Hardcoded string found')
  - (384, 'Hardcoded string found')
  - (385, 'Line exceeds 80 characters')
  - (385, 'Hardcoded string found')
  - (388, 'Hardcoded string found')
  - (389, 'Line exceeds 80 characters')
  - (389, 'Hardcoded string found')
  - (390, 'Line exceeds 80 characters')
  - (390, 'Hardcoded string found')
  - (391, 'Hardcoded string found')
  - (394, 'Hardcoded string found')
  - (399, 'Hardcoded string found')
  - (401, 'Hardcoded string found')
  - (402, 'Line exceeds 80 characters')
  - (402, 'Hardcoded string found')
  - (403, 'Line exceeds 80 characters')
  - (403, 'Hardcoded string found')
  - (404, 'Hardcoded string found')
  - (409, 'Hardcoded string found')
  - (410, 'Line exceeds 80 characters')
  - (410, 'Hardcoded string found')
  - (411, 'Line exceeds 80 characters')
  - (411, 'Hardcoded string found')
  - (416, 'Hardcoded string found')
  - (417, 'Line exceeds 80 characters')
  - (417, 'Hardcoded string found')
  - (421, 'Hardcoded string found')
  - (422, 'Line exceeds 80 characters')
  - (422, 'Hardcoded string found')
  - (423, 'Line exceeds 80 characters')
  - (423, 'Hardcoded string found')
  - (424, 'Hardcoded string found')
  - (425, 'Hardcoded string found')
  - (430, 'Hardcoded string found')
  - (431, 'Line exceeds 80 characters')
  - (431, 'Hardcoded string found')
  - (432, 'Line exceeds 80 characters')
  - (432, 'Hardcoded string found')
  - (433, 'Hardcoded string found')
  - (434, 'Hardcoded string found')
  - (440, 'Hardcoded string found')
  - (441, 'Hardcoded string found')
  - (442, 'Hardcoded string found')
  - (443, 'Line exceeds 80 characters')
  - (443, 'Hardcoded string found')
  - (444, 'Hardcoded string found')
  - (450, 'Hardcoded string found')
  - (451, 'Line exceeds 80 characters')
  - (451, 'Hardcoded string found')
  - (452, 'Line exceeds 80 characters')
  - (452, 'Hardcoded string found')
  - (454, 'Hardcoded string found')
  - (455, 'Hardcoded string found')
  - (456, 'Line exceeds 80 characters')
  - (456, 'Hardcoded string found')
  - (458, 'Hardcoded string found')
  - (459, 'Hardcoded string found')
  - (460, 'Hardcoded string found')
  - (461, 'Hardcoded string found')
  - (462, 'Hardcoded string found')
  - (463, 'Hardcoded string found')
  - (469, 'Hardcoded string found')
  - (470, 'Line exceeds 80 characters')
  - (470, 'Hardcoded string found')
  - (471, 'Line exceeds 80 characters')
  - (471, 'Hardcoded string found')
  - (472, 'Hardcoded string found')
  - (473, 'Hardcoded string found')
  - (478, 'Hardcoded string found')
  - (479, 'Line exceeds 80 characters')
  - (479, 'Hardcoded string found')
  - (480, 'Line exceeds 80 characters')
  - (480, 'Hardcoded string found')
  - (481, 'Hardcoded string found')
  - (483, 'Hardcoded string found')
  - (487, 'Hardcoded string found')
  - (488, 'Line exceeds 80 characters')
  - (488, 'Hardcoded string found')
  - (489, 'Line exceeds 80 characters')
  - (489, 'Hardcoded string found')
  - (490, 'Hardcoded string found')
  - (491, 'Hardcoded string found')
  - (492, 'Hardcoded string found')
  - (496, 'Hardcoded string found')
  - (497, 'Line exceeds 80 characters')
  - (497, 'Hardcoded string found')
  - (498, 'Line exceeds 80 characters')
  - (498, 'Hardcoded string found')
  - (499, 'Hardcoded string found')
  - (500, 'Hardcoded string found')
  - (505, 'Hardcoded string found')
  - (506, 'Line exceeds 80 characters')
  - (506, 'Hardcoded string found')
  - (507, 'Line exceeds 80 characters')
  - (507, 'Hardcoded string found')
  - (508, 'Hardcoded string found')
  - (509, 'Hardcoded string found')
  - (514, 'Hardcoded string found')
  - (515, 'Hardcoded string found')
  - (516, 'Hardcoded string found')
  - (517, 'Line exceeds 80 characters')
  - (517, 'Hardcoded string found')
  - (518, 'Hardcoded string found')
  - (519, 'Hardcoded string found')
  - (521, 'Hardcoded string found')
  - (523, 'Hardcoded string found')
  - (524, 'Hardcoded string found')
  - (525, 'Hardcoded string found')
  - (526, 'Hardcoded string found')
  - (527, 'Hardcoded string found')
  - (534, 'Hardcoded string found')
  - (535, 'Line exceeds 80 characters')
  - (535, 'Hardcoded string found')
  - (536, 'Line exceeds 80 characters')
  - (536, 'Hardcoded string found')
  - (539, 'Hardcoded string found')
  - (540, 'Line exceeds 80 characters')
  - (540, 'Hardcoded string found')
  - (544, 'Hardcoded string found')
  - (545, 'Line exceeds 80 characters')
  - (545, 'Hardcoded string found')
  - (546, 'Line exceeds 80 characters')
  - (546, 'Hardcoded string found')
  - (547, 'Hardcoded string found')
  - (548, 'Hardcoded string found')
  - (553, 'Hardcoded string found')
  - (554, 'Line exceeds 80 characters')
  - (554, 'Hardcoded string found')
  - (555, 'Line exceeds 80 characters')
  - (555, 'Hardcoded string found')
  - (556, 'Hardcoded string found')
  - (557, 'Hardcoded string found')
Issues in package.json:
  - (3, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in src/index.js:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
Issues in src/reducers/index.js:
  - (2, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
