### ISSUE TITLE
Issue-Adds Redux / Get Coin List Moved to Redux

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#103]
Automated Review Comments
Issues in package-lock.json:
  - (2, 'Hardcoded string found')
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in src/actions/index.js:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
Issues in src/components/BitcoinTracker.js:
  - (2, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
Issues in src/components/CoinList.js:
  - (7, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
