### ISSUE TITLE
Issue-Adds Get Price Handler to Redux

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#105]
Automated Review Comments
Issues in src/actions/index.js:
  - (2, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
Issues in src/components/BitcoinTracker.js:
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
Issues in src/reducers/coins.js:
  - (3, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
