### ISSUE TITLE
Issue-Refactors Get Coin Handler

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#107]
Automated Review Comments
Issues in src/actions/index.js:
  - (3, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
Issues in src/components/BitcoinTracker.js:
  - (14, 'Hardcoded string found')
Issues in src/reducers/coins.js:
  - (1, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
