### ISSUE TITLE
Issue-Adds Coin Add Handler to Redux

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#109]
Automated Review Comments
Issues in src/actions/index.js:
  - (2, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
Issues in src/reducers/coins.js:
  - (2, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
