### ISSUE TITLE
Issue-Moves styles out into own folder

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#119]
Automated Review Comments
Issues in src/components/BitcoinTracker.tsx:
  - (8, 'Hardcoded string found')
Issues in src/components/Coin.tsx:
  - (2, 'Hardcoded string found')
Issues in src/components/CoinList.tsx:
  - (2, 'Hardcoded string found')
Issues in src/components/ControlPanel.tsx:
  - (2, 'Hardcoded string found')
Issues in src/components/Footer.tsx:
  - (2, 'Hardcoded string found')
Issues in src/index.tsx:
  - (2, 'Hardcoded string found')
Issues in src/styles/main.sass:
  - (14, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
