### ISSUE TITLE
Issue-Adds updated readme

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#137]
Automated Review Comments
Issues in README.md:
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
