### ISSUE TITLE
Issue-Footer refactor

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#149]
Automated Review Comments
Issues in src/components/Footer.tsx:
  - (2, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
