### ISSUE TITLE
Issue-Fixes footer styling

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#159]
Automated Review Comments
Issues in src/components/App.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (55, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
