### ISSUE TITLE
Issue-Switches from thunk to sagas

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#163]
Automated Review Comments
Issues in package-lock.json:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (38, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
  - (43, 'Line exceeds 80 characters')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Line exceeds 80 characters')
  - (59, 'Hardcoded string found')
  - (60, 'Line exceeds 80 characters')
  - (60, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (64, 'Line exceeds 80 characters')
  - (64, 'Hardcoded string found')
  - (65, 'Line exceeds 80 characters')
  - (65, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (69, 'Line exceeds 80 characters')
  - (69, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (72, 'Line exceeds 80 characters')
  - (72, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (77, 'Line exceeds 80 characters')
  - (77, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (86, 'Line exceeds 80 characters')
  - (86, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (93, 'Line exceeds 80 characters')
  - (93, 'Hardcoded string found')
  - (94, 'Line exceeds 80 characters')
  - (94, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (101, 'Line exceeds 80 characters')
  - (101, 'Hardcoded string found')
  - (102, 'Line exceeds 80 characters')
  - (102, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (108, 'Line exceeds 80 characters')
  - (108, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (115, 'Line exceeds 80 characters')
  - (115, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (118, 'Line exceeds 80 characters')
  - (118, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (126, 'Line exceeds 80 characters')
  - (126, 'Hardcoded string found')
  - (127, 'Line exceeds 80 characters')
  - (127, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (130, 'Line exceeds 80 characters')
  - (130, 'Hardcoded string found')
  - (131, 'Line exceeds 80 characters')
  - (131, 'Hardcoded string found')
  - (132, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (139, 'Line exceeds 80 characters')
  - (139, 'Hardcoded string found')
  - (140, 'Hardcoded string found')
  - (143, 'Hardcoded string found')
  - (144, 'Line exceeds 80 characters')
  - (144, 'Hardcoded string found')
  - (145, 'Line exceeds 80 characters')
  - (145, 'Hardcoded string found')
  - (147, 'Hardcoded string found')
  - (148, 'Hardcoded string found')
  - (149, 'Line exceeds 80 characters')
  - (149, 'Hardcoded string found')
  - (150, 'Line exceeds 80 characters')
  - (150, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (154, 'Line exceeds 80 characters')
  - (154, 'Hardcoded string found')
  - (155, 'Line exceeds 80 characters')
  - (155, 'Hardcoded string found')
  - (156, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
  - (162, 'Line exceeds 80 characters')
  - (162, 'Hardcoded string found')
  - (163, 'Line exceeds 80 characters')
  - (163, 'Hardcoded string found')
  - (166, 'Hardcoded string found')
  - (167, 'Line exceeds 80 characters')
  - (167, 'Hardcoded string found')
  - (168, 'Line exceeds 80 characters')
  - (168, 'Hardcoded string found')
  - (169, 'Hardcoded string found')
  - (174, 'Hardcoded string found')
  - (175, 'Line exceeds 80 characters')
  - (175, 'Hardcoded string found')
Issues in package.json:
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
Issues in src/components/App.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
Issues in src/components/Coin.tsx:
  - (2, 'Hardcoded string found')
Issues in src/components/CoinList.tsx:
  - (2, 'Hardcoded string found')
Issues in src/components/ControlPanel.tsx:
  - (2, 'Hardcoded string found')
Issues in src/index.tsx:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
Issues in src/redux/coins/actions.ts:
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
Issues in src/redux/coins/reducer.ts:
  - (2, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (62, 'Line exceeds 80 characters')
Issues in src/redux/coins/sagas.ts:
  - (4, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
Issues in src/redux/index.ts:
  - (2, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (48, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (60, 'Hardcoded string found')
  - (64, 'Line exceeds 80 characters')
  - (66, 'Line exceeds 80 characters')
  - (71, 'Line exceeds 80 characters')
  - (71, 'Hardcoded string found')
Issues in src/utils/configureStore.ts:
  - (3, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
