### ISSUE TITLE
Issue-Adds config util

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#165]
Automated Review Comments
Issues in src/index.tsx:
  - (1, 'Hardcoded string found')
Issues in src/redux/coins/sagas.ts:
  - (2, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
Issues in src/utils/config.ts:
  - (3, 'Line exceeds 80 characters')

**Comment by johnsmith0212** [comment]
I got it.
