### ISSUE TITLE
Issue-Adds font awesome

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#169]
Automated Review Comments
Issues in package-lock.json:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (44, 'Line exceeds 80 characters')
  - (44, 'Hardcoded string found')
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
Issues in public/index.html:
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
Issues in src/components/Footer.tsx:
  - (2, 'Hardcoded string found')
  - (22, 'Hardcoded string found')

**Comment by johnsmith0212** [comment]
I got it.
