### ISSUE TITLE
Issue-Adds loading indicator

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#173]
Automated Review Comments
Issues in src/components/App.tsx:
  - (2, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
Issues in src/components/CoinList.tsx:
  - (2, 'Hardcoded string found')
Issues in src/components/ui/LoadingPanel.tsx:
  - (2, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
Issues in src/components/ui/LoadingSpinner.tsx:
  - (2, 'Hardcoded string found')
Issues in src/styles/loading-spinner.sass:
  - (8, 'Hardcoded string found')

**Comment by johnsmith0212** [comment]
I got it.
