### ISSUE TITLE
Issue-Makes refresh icon spin on load

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#175]
Automated Review Comments
Issues in src/components/App.tsx:
  - (4, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in src/components/Header.tsx:
  - (26, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')

**Comment by 0x0factor** [comment]
I got it.
