### ISSUE TITLE
Issue-Adds news feed redux

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#177]
Automated Review Comments
Issues in src/components/App.tsx:
  - (12, 'Hardcoded string found')
Issues in src/components/news/NewsFeed.tsx:
  - (2, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
Issues in src/components/news/NewsItem.tsx:
  - (2, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
Issues in src/redux/index.ts:
  - (2, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in src/redux/news/actions.ts:
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
Issues in src/redux/news/reducer.ts:
  - (2, 'Hardcoded string found')
Issues in src/redux/news/sagas.ts:
  - (10, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')

**Comment by 0x0factor** [comment]
I got it.
