### ISSUE TITLE
Issue-Adds news components & fixes veiw height

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#179]
Automated Review Comments
Issues in src/components/Footer.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
Issues in src/components/news/NewsFeed.tsx:
  - (2, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
Issues in src/components/news/NewsItem.tsx:
  - (2, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')

**Comment by 0x0factor** [comment]
I got it.
