### ISSUE TITLE
Issue-Adds currency toggle

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#183]
Automated Review Comments
Issues in src/components/App.tsx:
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
Issues in src/components/Header.tsx:
  - (10, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
Issues in src/components/coins/Coin.tsx:
  - (4, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
Issues in src/utils/iconConfig.ts:
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')

**Comment by 0x0factor** [comment]
I got it.
