### ISSUE TITLE
Issue-File renaming

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#189]
Automated Review Comments
Issues in src/components/Header.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in src/components/coins/CoinList.tsx:
  - (2, 'Hardcoded string found')
Issues in src/components/coins/CoinListItem.tsx:
  - (2, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
Issues in src/components/coins/FullCoinList.tsx:
  - (2, 'Hardcoded string found')

**Comment by 0x0factor** [comment]
I got it.
