### ISSUE TITLE
Issue-Adds icons and makes it possible to toggle coin favs

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#193]
Automated Review Comments
Issues in package-lock.json:
  - (6, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
Issues in package.json:
  - (2, 'Hardcoded string found')
Issues in src/components/coins/CoinListItem.tsx:
  - (2, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
Issues in src/utils/iconConfig.ts:
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')

**Comment by 0x0factor** [comment]
I got it.
