### ISSUE TITLE
Issue-Moves favourites into config

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#195]
Automated Review Comments
Issues in src/redux/coins/reducer.ts:
  - (2, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'TODO found')
  - (20, 'Line exceeds 80 characters')
Issues in src/utils/config.ts:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')

**Comment by 0x0factor** [comment]
I got it.
