### ISSUE TITLE
Issue-Improves responsiveness tidies variables

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#198]
Automated Review Comments
Issues in src/components/App.tsx:
  - (3, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
Issues in src/components/Header.tsx:
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
Issues in src/components/coins/CoinListItem.tsx:
  - (11, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
