### ISSUE TITLE
Issue-Adds refresh for news feed

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#220]
Automated Review Comments
Issues in src/components/Header.tsx:
  - (2, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (38, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
Issues in src/components/api/newsFeed.ts:
  - (19, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
Issues in src/components/news/NewsFeed.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
Issues in src/components/news/NewsItem.tsx:
  - (2, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
