### ISSUE TITLE
Issue-Fix favourite toggle handler

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#224]
Automated Review Comments
Issues in src/components/coins/CoinList.tsx:
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
Issues in src/components/coins/CoinListItem.tsx:
  - (2, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
Issues in src/components/coins/FullCoinList.tsx:
  - (24, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
