### ISSUE TITLE
Issue-Memoisation where possible

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#226]
Automated Review Comments
Issues in src/components/App.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
Issues in src/components/Footer.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
Issues in src/components/Header.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
Issues in src/components/coins/CoinListItem.tsx:
  - (5, 'TODO found')
  - (7, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (13, 'TODO found')
Issues in src/components/news/NewsItem.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
