### ISSUE TITLE
Issue-Uses enum for action types

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#234]
Automated Review Comments
Issues in src/components/Header.tsx:
  - (6, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
Issues in src/components/coins/CoinListItem.tsx:
  - (2, 'Hardcoded string found')
Issues in src/utils/GlobalStateProvider.tsx:
  - (5, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
