### ISSUE TITLE
Issue-Moves queries into lower components

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#238]
Automated Review Comments
Issues in src/components/App.tsx:
  - (2, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')
Issues in src/components/coins/CoinList.tsx:
  - (1, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (34, 'TODO found')
  - (35, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
Issues in src/components/coins/FullCoinList.tsx:
  - (1, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
