### ISSUE TITLE
Issue-Tidies up query placing into a custom hook

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#240]
Automated Review Comments
Issues in src/components/App.tsx:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in src/components/coins/CoinList.tsx:
  - (1, 'Hardcoded string found')
  - (24, 'TODO found')
  - (25, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (67, 'Line exceeds 80 characters')
Issues in src/components/coins/CoinListItem.tsx:
  - (8, 'TODO found')
  - (9, 'Line exceeds 80 characters')
  - (13, 'TODO found')
  - (14, 'TODO found')
  - (24, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
Issues in src/components/coins/FullCoinList.tsx:
  - (1, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
Issues in src/components/hooks/useCoinDataQuery.ts:
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
