### ISSUE TITLE
Issue-Makes pagination a reusable component

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#242]
Automated Review Comments
Issues in src/components/coins/FullCoinList.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
Issues in src/components/ui/pagination/PaginatedList.tsx:
  - (2, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
Issues in src/components/ui/pagination/PaginationControl.tsx:
  - (2, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
Issues in src/components/ui/pagination/utils.ts:
  - (4, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
