### ISSUE TITLE
Issue-Moves price formatter into utils

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#244]
Automated Review Comments
Issues in src/components/coins/CoinListItem.tsx:
  - (1, 'Hardcoded string found')
  - (13, 'TODO found')
  - (15, 'Hardcoded string found')
  - (23, 'TODO found')
Issues in src/components/coins/utils.ts:
  - (6, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
