### ISSUE TITLE
Issue-Restructures global state

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#246]
Automated Review Comments
Issues in src/components/Header.tsx:
  - (5, 'Line exceeds 80 characters')
Issues in src/components/coins/CoinListItem.tsx:
  - (2, 'Hardcoded string found')
Issues in src/components/global-state/GlobalStateProvider.tsx:
  - (2, 'Hardcoded string found')
Issues in src/components/global-state/hooks.tsx:
  - (2, 'Hardcoded string found')
Issues in src/components/global-state/reducer.ts:
  - (10, 'Line exceeds 80 characters')
Issues in src/components/global-state/types.ts:
  - (2, 'Hardcoded string found')
Issues in src/index.tsx:
  - (6, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
