### ISSUE TITLE
Issue-ci: removes circle ci setup and adds pr template

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#255]
Automated Review Comments
Issues in .github/pull-request-template.md:
  - (11, 'Line exceeds 80 characters')
Issues in README.md:
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
