### ISSUE TITLE
Issue-chore: updates packages moves dev deps out of normal deps

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#259]
Automated Review Comments
Issues in package.json:
  - (9, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
Issues in src/components/ui/pagination/PaginatedList.tsx:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
Issues in tsconfig.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
