### ISSUE TITLE
Issue-fix: updates to react 18 create dom setup

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#284]
Automated Review Comments
Issues in public/manifest.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
Issues in src/index.tsx:
  - (2, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (27, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
