### ISSUE TITLE
Issue-tests: adds test config for icons and custom render wrapper

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#324]
Automated Review Comments
Issues in docs/CHANGELOG.md:
  - (2, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
Issues in src/test/testSetup.ts:
  - (3, 'Hardcoded string found')
Issues in src/test/testUtils.tsx:
  - (2, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
