### ISSUE TITLE
Issue-tests: adds test to validate script

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#331]
Automated Review Comments
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
