### ISSUE TITLE
Issue-tests: adds basic tests for footer

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#343]
Automated Review Comments
Issues in src/components/Footer.test.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
