### ISSUE TITLE
Issue-refactor: adds loading indicator test and moves loading spinner into panel

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#345]
Automated Review Comments
Issues in src/components/ui/LoadingPanel.test.tsx:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
Issues in src/components/ui/LoadingPanel.tsx:
  - (2, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
