### ISSUE TITLE
Issue-tests: adds accessability and tests for pagination controls

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#351]
Automated Review Comments
Issues in src/components/ui/pagination/PaginationControl.test.tsx:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')
Issues in src/components/ui/pagination/PaginationControl.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
