### ISSUE TITLE
Issue-tests: general test coverage improvements

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#353]
Automated Review Comments
Issues in src/components/api/coin.test.ts:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
Issues in src/components/api/newsFeed.test.ts:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
Issues in src/components/global-state/GlobalStateProvider.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
Issues in src/components/global-state/reducer.test.ts:
  - (6, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (49, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
