### ISSUE TITLE
Issue-tests: adds tests for pagination util

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#355]
Automated Review Comments
Issues in src/components/ui/pagination/utils.test.ts:
  - (4, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (45, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
