### ISSUE TITLE
Issue-tests: removes old global state and fixes all tests

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#365]
Automated Review Comments
Issues in src/components/Footer.test.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
Issues in src/components/Header.test.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (40, 'Hardcoded string found')
Issues in src/components/Header.tsx:
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
Issues in src/components/coins/CoinListItem.test.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (45, 'Hardcoded string found')
Issues in src/main.tsx:
  - (2, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
Issues in src/store/index.ts:
  - (2, 'Hardcoded string found')
Issues in src/test/StoreTestProviders.tsx:
  - (2, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
