### ISSUE TITLE
Issue-ci: overhauls ci and release worklows

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#371]
Automated Review Comments
Issues in .github/workflows/ci.yaml:
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
Issues in .github/workflows/release.yaml:
  - (65, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
