### ISSUE TITLE
Issue-refactor: converts all imports to aliased and removes coupling in queries

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#383]
Automated Review Comments
Issues in .eslintrc.cjs:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
Issues in src/components/App.tsx:
  - (2, 'Hardcoded string found')
Issues in src/components/Footer.test.tsx:
  - (3, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in src/components/Footer.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
Issues in src/components/Header.test.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
Issues in src/components/Header.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (49, 'Line exceeds 80 characters')
  - (49, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (52, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (53, 'Hardcoded string found')
Issues in src/components/ui/pagination/PaginatedList.tsx:
  - (2, 'Hardcoded string found')
Issues in src/components/ui/pagination/createPaginationArray.ts:
  - (5, 'Line exceeds 80 characters')
Issues in src/config/icon.ts:
  - (4, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
Issues in src/config/index.ts:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
Issues in src/features/coin-list/api/coin.test.ts:
  - (2, 'Hardcoded string found')
Issues in src/features/coin-list/api/coins.ts:
  - (9, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
Issues in src/features/coin-list/components/CoinListItem.test.tsx:
  - (2, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
Issues in src/features/coin-list/components/CoinListItem.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
Issues in src/features/coin-list/hooks/useCoinDataQuery.ts:
  - (17, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
Issues in src/features/coin-list/routes/CoinList.tsx:
  - (3, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
Issues in src/features/coin-list/routes/FullCoinList.tsx:
  - (2, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
Issues in src/features/news/api/getNews.test.ts:
  - (2, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in src/features/news/api/getNews.ts:
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
Issues in src/features/news/components/NewsItem.tsx:
  - (2, 'Hardcoded string found')
Issues in src/features/news/routes/NewsFeed.tsx:
  - (10, 'Line exceeds 80 characters')
Issues in src/main.tsx:
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in src/store/global.ts:
  - (2, 'Hardcoded string found')
Issues in src/test/testSetup.ts:
  - (4, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
