### ISSUE TITLE
Issue-tests: reimplements refresh tests

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#391]
Automated Review Comments
Issues in src/components/Header.test.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
Issues in src/components/Header.tsx:
  - (7, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
