### ISSUE TITLE
Issue-fix: fixes minor audit issues

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#397]
Automated Review Comments
Issues in package-lock.json:
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Line exceeds 80 characters')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
