### ISSUE TITLE
Issue-feat: adds theme styling

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#409]
Automated Review Comments
Issues in index.html:
  - (3, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
Issues in src/styles/index.sass:
  - (4, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
Issues in src/styles/loading-spinner.sass:
  - (8, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
