### ISSUE TITLE
Issue-feat: adds local storage for persisting user theme choice

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#417]
Automated Review Comments
Issues in src/hooks/useTheme.ts:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (39, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
