### ISSUE TITLE
Issue-Added New Coin Submit Logic

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#46]
Automated Review Comments
Issues in src/__tests__/__snapshots__/BitcoinTracker.test.js.snap:
  - (10, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
