### ISSUE TITLE
Issue-Add Delete Click Handler

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#59]
Automated Review Comments
Issues in src/__tests__/__snapshots__/BitcoinTracker.test.js.snap:
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
Issues in src/__tests__/__snapshots__/CoinList.test.js.snap:
  - (8, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
Issues in src/components/Coin.js:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
Issues in src/components/CoinList.js:
  - (2, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
