### ISSUE TITLE
Issue-Improved Logo

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#63]
Automated Review Comments
Issues in index.html:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in src/main.sass:
  - (11, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
