### ISSUE TITLE
Issue-Add Footer

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#65]
Automated Review Comments
Issues in src/__tests__/__snapshots__/ControlPanel.test.js.snap:
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
Issues in src/components/BitcoinTracker.js:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
