### ISSUE TITLE
Issue-Add Footer Component

Moved footer into a new component reused from another project.

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#67]
Automated Review Comments
Issues in src/__tests__/Footer.test.js:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in src/__tests__/__snapshots__/BitcoinTracker.test.js.snap:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (97, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (111, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (132, 'Hardcoded string found')
  - (133, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (142, 'Hardcoded string found')
  - (143, 'Hardcoded string found')
  - (144, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (148, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (150, 'Hardcoded string found')
  - (151, 'Hardcoded string found')
  - (154, 'Hardcoded string found')
  - (156, 'Hardcoded string found')
  - (157, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
  - (165, 'Hardcoded string found')
  - (166, 'Hardcoded string found')
  - (167, 'Hardcoded string found')
  - (168, 'Hardcoded string found')
  - (169, 'Hardcoded string found')
  - (171, 'Hardcoded string found')
  - (199, 'Hardcoded string found')
  - (200, 'Hardcoded string found')
  - (202, 'Hardcoded string found')
  - (203, 'Hardcoded string found')
  - (204, 'Hardcoded string found')
  - (205, 'Hardcoded string found')
  - (206, 'Hardcoded string found')
  - (215, 'Hardcoded string found')
  - (216, 'Hardcoded string found')
  - (217, 'Hardcoded string found')
  - (218, 'Hardcoded string found')
  - (233, 'Hardcoded string found')
  - (234, 'Hardcoded string found')
  - (235, 'Hardcoded string found')
  - (236, 'Hardcoded string found')
  - (239, 'Hardcoded string found')
  - (240, 'Hardcoded string found')
  - (241, 'Hardcoded string found')
  - (242, 'Hardcoded string found')
  - (245, 'Hardcoded string found')
  - (246, 'Hardcoded string found')
  - (247, 'Hardcoded string found')
  - (248, 'Hardcoded string found')
  - (251, 'Hardcoded string found')
  - (252, 'Hardcoded string found')
  - (253, 'Hardcoded string found')
  - (254, 'Hardcoded string found')
  - (257, 'Hardcoded string found')
  - (258, 'Hardcoded string found')
  - (259, 'Hardcoded string found')
  - (260, 'Hardcoded string found')
  - (263, 'Hardcoded string found')
  - (264, 'Hardcoded string found')
  - (265, 'Hardcoded string found')
  - (266, 'Hardcoded string found')
  - (273, 'Hardcoded string found')
  - (275, 'Hardcoded string found')
  - (276, 'Hardcoded string found')
  - (278, 'Hardcoded string found')
  - (279, 'Hardcoded string found')
  - (280, 'Hardcoded string found')
  - (281, 'Hardcoded string found')
  - (282, 'Hardcoded string found')
  - (284, 'Hardcoded string found')
  - (285, 'Hardcoded string found')
  - (286, 'Hardcoded string found')
  - (289, 'Hardcoded string found')
  - (290, 'Hardcoded string found')
  - (291, 'Hardcoded string found')
  - (292, 'Hardcoded string found')
  - (293, 'Hardcoded string found')
  - (294, 'Hardcoded string found')
  - (296, 'Hardcoded string found')
  - (297, 'Hardcoded string found')
  - (298, 'Hardcoded string found')
  - (299, 'Hardcoded string found')
  - (302, 'Hardcoded string found')
  - (303, 'Hardcoded string found')
  - (305, 'Hardcoded string found')
  - (306, 'Hardcoded string found')
  - (307, 'Hardcoded string found')
  - (310, 'Hardcoded string found')
  - (311, 'Hardcoded string found')
  - (312, 'Hardcoded string found')
  - (313, 'Hardcoded string found')
  - (314, 'Hardcoded string found')
  - (315, 'Hardcoded string found')
  - (316, 'Hardcoded string found')
  - (317, 'Hardcoded string found')
  - (318, 'Hardcoded string found')
  - (320, 'Hardcoded string found')
  - (321, 'Hardcoded string found')
  - (322, 'Hardcoded string found')
  - (323, 'Hardcoded string found')
  - (326, 'Hardcoded string found')
  - (327, 'Hardcoded string found')
  - (328, 'Hardcoded string found')
  - (329, 'Hardcoded string found')
  - (332, 'Hardcoded string found')
  - (333, 'Hardcoded string found')
  - (334, 'Hardcoded string found')
  - (335, 'Hardcoded string found')
  - (338, 'Hardcoded string found')
  - (339, 'Hardcoded string found')
  - (340, 'Hardcoded string found')
  - (341, 'Hardcoded string found')
  - (344, 'Hardcoded string found')
  - (345, 'Hardcoded string found')
  - (346, 'Hardcoded string found')
  - (347, 'Hardcoded string found')
  - (350, 'Hardcoded string found')
  - (351, 'Hardcoded string found')
  - (352, 'Hardcoded string found')
  - (353, 'Hardcoded string found')
  - (356, 'Hardcoded string found')
  - (358, 'Hardcoded string found')
  - (359, 'Hardcoded string found')
  - (360, 'Hardcoded string found')
  - (363, 'Hardcoded string found')
  - (366, 'Hardcoded string found')
  - (367, 'Hardcoded string found')
  - (368, 'Hardcoded string found')
  - (369, 'Hardcoded string found')
  - (370, 'Hardcoded string found')
  - (371, 'Hardcoded string found')
  - (372, 'Hardcoded string found')
  - (375, 'Hardcoded string found')
  - (379, 'Hardcoded string found')
  - (380, 'Hardcoded string found')
  - (381, 'Hardcoded string found')
  - (382, 'Hardcoded string found')
  - (383, 'Hardcoded string found')
  - (385, 'Hardcoded string found')
  - (395, 'Hardcoded string found')
  - (396, 'Hardcoded string found')
  - (397, 'Hardcoded string found')
  - (398, 'Hardcoded string found')
  - (413, 'Hardcoded string found')
  - (414, 'Hardcoded string found')
  - (415, 'Hardcoded string found')
  - (416, 'Hardcoded string found')
  - (419, 'Hardcoded string found')
  - (420, 'Hardcoded string found')
  - (421, 'Hardcoded string found')
  - (422, 'Hardcoded string found')
  - (425, 'Hardcoded string found')
  - (426, 'Hardcoded string found')
  - (427, 'Hardcoded string found')
  - (428, 'Hardcoded string found')
  - (431, 'Hardcoded string found')
  - (432, 'Hardcoded string found')
  - (433, 'Hardcoded string found')
  - (434, 'Hardcoded string found')
  - (437, 'Hardcoded string found')
  - (438, 'Hardcoded string found')
  - (439, 'Hardcoded string found')
  - (440, 'Hardcoded string found')
  - (443, 'Hardcoded string found')
  - (444, 'Hardcoded string found')
  - (445, 'Hardcoded string found')
  - (446, 'Hardcoded string found')
  - (455, 'Hardcoded string found')
  - (457, 'Hardcoded string found')
  - (458, 'Hardcoded string found')
  - (460, 'Hardcoded string found')
  - (461, 'Hardcoded string found')
  - (462, 'Hardcoded string found')
  - (463, 'Hardcoded string found')
  - (465, 'Hardcoded string found')
  - (466, 'Hardcoded string found')
  - (467, 'Hardcoded string found')
  - (470, 'Hardcoded string found')
  - (471, 'Hardcoded string found')
  - (472, 'Hardcoded string found')
  - (473, 'Hardcoded string found')
  - (474, 'Hardcoded string found')
  - (475, 'Hardcoded string found')
  - (477, 'Hardcoded string found')
  - (478, 'Hardcoded string found')
  - (479, 'Hardcoded string found')
  - (480, 'Hardcoded string found')
  - (482, 'Hardcoded string found')
  - (491, 'Hardcoded string found')
  - (492, 'Hardcoded string found')
  - (493, 'Hardcoded string found')
  - (494, 'Hardcoded string found')
  - (509, 'Hardcoded string found')
  - (510, 'Hardcoded string found')
  - (511, 'Hardcoded string found')
  - (512, 'Hardcoded string found')
  - (515, 'Hardcoded string found')
  - (516, 'Hardcoded string found')
  - (517, 'Hardcoded string found')
  - (518, 'Hardcoded string found')
  - (521, 'Hardcoded string found')
  - (522, 'Hardcoded string found')
  - (523, 'Hardcoded string found')
  - (524, 'Hardcoded string found')
  - (527, 'Hardcoded string found')
  - (528, 'Hardcoded string found')
  - (529, 'Hardcoded string found')
  - (530, 'Hardcoded string found')
  - (533, 'Hardcoded string found')
  - (534, 'Hardcoded string found')
  - (535, 'Hardcoded string found')
  - (536, 'Hardcoded string found')
  - (539, 'Hardcoded string found')
  - (540, 'Hardcoded string found')
  - (541, 'Hardcoded string found')
  - (542, 'Hardcoded string found')
  - (549, 'Hardcoded string found')
  - (550, 'Hardcoded string found')
  - (551, 'Hardcoded string found')
  - (553, 'Hardcoded string found')
  - (554, 'Hardcoded string found')
  - (555, 'Hardcoded string found')
  - (556, 'Hardcoded string found')
  - (558, 'Hardcoded string found')
  - (559, 'Hardcoded string found')
  - (560, 'Hardcoded string found')
  - (561, 'Hardcoded string found')
  - (562, 'Hardcoded string found')
  - (564, 'Hardcoded string found')
  - (565, 'Hardcoded string found')
  - (566, 'Hardcoded string found')
  - (569, 'Hardcoded string found')
  - (570, 'Hardcoded string found')
  - (571, 'Hardcoded string found')
  - (572, 'Hardcoded string found')
  - (573, 'Hardcoded string found')
  - (574, 'Hardcoded string found')
  - (576, 'Hardcoded string found')
  - (577, 'Hardcoded string found')
  - (578, 'Hardcoded string found')
  - (579, 'Hardcoded string found')
  - (582, 'Hardcoded string found')
  - (583, 'Hardcoded string found')
  - (585, 'Hardcoded string found')
  - (586, 'Hardcoded string found')
  - (587, 'Hardcoded string found')
  - (590, 'Hardcoded string found')
  - (591, 'Hardcoded string found')
  - (592, 'Hardcoded string found')
  - (593, 'Hardcoded string found')
  - (594, 'Hardcoded string found')
  - (595, 'Hardcoded string found')
  - (596, 'Hardcoded string found')
  - (597, 'Hardcoded string found')
  - (598, 'Hardcoded string found')
  - (600, 'Hardcoded string found')
  - (601, 'Hardcoded string found')
  - (602, 'Hardcoded string found')
  - (603, 'Hardcoded string found')
  - (606, 'Hardcoded string found')
  - (607, 'Hardcoded string found')
  - (608, 'Hardcoded string found')
  - (609, 'Hardcoded string found')
  - (612, 'Hardcoded string found')
  - (613, 'Hardcoded string found')
  - (614, 'Hardcoded string found')
  - (615, 'Hardcoded string found')
  - (618, 'Hardcoded string found')
  - (619, 'Hardcoded string found')
  - (620, 'Hardcoded string found')
  - (621, 'Hardcoded string found')
  - (624, 'Hardcoded string found')
  - (625, 'Hardcoded string found')
  - (626, 'Hardcoded string found')
  - (627, 'Hardcoded string found')
  - (630, 'Hardcoded string found')
  - (631, 'Hardcoded string found')
  - (632, 'Hardcoded string found')
  - (633, 'Hardcoded string found')
  - (636, 'Hardcoded string found')
  - (638, 'Hardcoded string found')
  - (639, 'Hardcoded string found')
  - (640, 'Hardcoded string found')
  - (643, 'Hardcoded string found')
  - (646, 'Hardcoded string found')
  - (647, 'Hardcoded string found')
  - (648, 'Hardcoded string found')
  - (649, 'Hardcoded string found')
  - (650, 'Hardcoded string found')
  - (651, 'Hardcoded string found')
  - (652, 'Hardcoded string found')
  - (653, 'Hardcoded string found')
  - (654, 'Hardcoded string found')
  - (656, 'Hardcoded string found')
  - (657, 'Hardcoded string found')
  - (658, 'Hardcoded string found')
  - (659, 'Hardcoded string found')
  - (662, 'Hardcoded string found')
  - (663, 'Hardcoded string found')
  - (664, 'Hardcoded string found')
  - (665, 'Hardcoded string found')
  - (668, 'Hardcoded string found')
  - (669, 'Hardcoded string found')
  - (670, 'Hardcoded string found')
  - (671, 'Hardcoded string found')
  - (674, 'Hardcoded string found')
  - (675, 'Hardcoded string found')
  - (676, 'Hardcoded string found')
  - (677, 'Hardcoded string found')
  - (680, 'Hardcoded string found')
  - (681, 'Hardcoded string found')
  - (682, 'Hardcoded string found')
  - (683, 'Hardcoded string found')
  - (686, 'Hardcoded string found')
  - (687, 'Hardcoded string found')
  - (688, 'Hardcoded string found')
  - (689, 'Hardcoded string found')
  - (692, 'Hardcoded string found')
  - (694, 'Hardcoded string found')
  - (695, 'Hardcoded string found')
  - (696, 'Hardcoded string found')
  - (697, 'Hardcoded string found')
  - (698, 'Hardcoded string found')
Issues in src/__tests__/__snapshots__/Footer.test.js.snap:
  - (6, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (97, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (102, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (132, 'Hardcoded string found')
  - (133, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (141, 'Hardcoded string found')
  - (142, 'Hardcoded string found')
  - (143, 'Hardcoded string found')
  - (144, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (147, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (150, 'Hardcoded string found')
  - (151, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (156, 'Hardcoded string found')
  - (157, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
  - (160, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (165, 'Hardcoded string found')
  - (166, 'Hardcoded string found')
  - (167, 'Hardcoded string found')
  - (168, 'Hardcoded string found')
  - (169, 'Hardcoded string found')
  - (170, 'Hardcoded string found')
  - (171, 'Hardcoded string found')
  - (173, 'Hardcoded string found')
  - (174, 'Hardcoded string found')
  - (175, 'Hardcoded string found')
  - (177, 'Hardcoded string found')
  - (180, 'Hardcoded string found')
  - (181, 'Hardcoded string found')
  - (182, 'Hardcoded string found')
  - (183, 'Hardcoded string found')
  - (184, 'Hardcoded string found')
  - (187, 'Hardcoded string found')
  - (189, 'Hardcoded string found')
  - (190, 'Hardcoded string found')
  - (191, 'Hardcoded string found')
  - (192, 'Hardcoded string found')
  - (193, 'Hardcoded string found')
  - (194, 'Hardcoded string found')
  - (195, 'Hardcoded string found')
  - (197, 'Hardcoded string found')
  - (198, 'Hardcoded string found')
  - (199, 'Hardcoded string found')
  - (201, 'Hardcoded string found')
  - (204, 'Hardcoded string found')
  - (207, 'Hardcoded string found')
  - (208, 'Hardcoded string found')
  - (209, 'Hardcoded string found')
  - (210, 'Hardcoded string found')
  - (211, 'Hardcoded string found')
  - (212, 'Hardcoded string found')
  - (220, 'Hardcoded string found')
  - (221, 'Hardcoded string found')
  - (222, 'Hardcoded string found')
  - (224, 'Hardcoded string found')
  - (225, 'Hardcoded string found')
  - (226, 'Hardcoded string found')
  - (227, 'Hardcoded string found')
  - (228, 'Hardcoded string found')
  - (229, 'Hardcoded string found')
  - (231, 'Hardcoded string found')
  - (232, 'Hardcoded string found')
  - (233, 'Hardcoded string found')
  - (236, 'Hardcoded string found')
  - (239, 'Hardcoded string found')
  - (243, 'Hardcoded string found')
  - (244, 'Hardcoded string found')
  - (245, 'Hardcoded string found')
  - (246, 'Hardcoded string found')
  - (247, 'Hardcoded string found')
  - (291, 'Hardcoded string found')
  - (292, 'Hardcoded string found')
  - (294, 'Hardcoded string found')
  - (295, 'Hardcoded string found')
  - (296, 'Hardcoded string found')
  - (297, 'Hardcoded string found')
  - (298, 'Hardcoded string found')
  - (299, 'Hardcoded string found')
  - (307, 'Hardcoded string found')
  - (308, 'Hardcoded string found')
  - (309, 'Hardcoded string found')
  - (311, 'Hardcoded string found')
  - (312, 'Hardcoded string found')
  - (313, 'Hardcoded string found')
  - (314, 'Hardcoded string found')
  - (315, 'Hardcoded string found')
  - (316, 'Hardcoded string found')
  - (318, 'Hardcoded string found')
  - (319, 'Hardcoded string found')
  - (320, 'Hardcoded string found')
  - (323, 'Hardcoded string found')
  - (326, 'Hardcoded string found')
  - (327, 'Hardcoded string found')
  - (328, 'Hardcoded string found')
  - (329, 'Hardcoded string found')
  - (330, 'Hardcoded string found')
  - (353, 'Hardcoded string found')
  - (355, 'Hardcoded string found')
  - (356, 'Hardcoded string found')
  - (358, 'Hardcoded string found')
  - (359, 'Hardcoded string found')
  - (360, 'Hardcoded string found')
  - (361, 'Hardcoded string found')
  - (362, 'Hardcoded string found')
  - (365, 'Hardcoded string found')
  - (367, 'Hardcoded string found')
  - (368, 'Hardcoded string found')
  - (369, 'Hardcoded string found')
  - (370, 'Hardcoded string found')
  - (371, 'Hardcoded string found')
  - (372, 'Hardcoded string found')
  - (373, 'Hardcoded string found')
  - (375, 'Hardcoded string found')
  - (376, 'Hardcoded string found')
  - (377, 'Hardcoded string found')
  - (379, 'Hardcoded string found')
  - (382, 'Hardcoded string found')
  - (383, 'Hardcoded string found')
  - (384, 'Hardcoded string found')
  - (385, 'Hardcoded string found')
  - (386, 'Hardcoded string found')
  - (389, 'Hardcoded string found')
  - (391, 'Hardcoded string found')
  - (392, 'Hardcoded string found')
  - (393, 'Hardcoded string found')
  - (394, 'Hardcoded string found')
  - (395, 'Hardcoded string found')
  - (396, 'Hardcoded string found')
  - (397, 'Hardcoded string found')
  - (399, 'Hardcoded string found')
  - (400, 'Hardcoded string found')
  - (401, 'Hardcoded string found')
  - (403, 'Hardcoded string found')
  - (406, 'Hardcoded string found')
  - (407, 'Hardcoded string found')
  - (408, 'Hardcoded string found')
  - (409, 'Hardcoded string found')
  - (410, 'Hardcoded string found')
  - (413, 'Hardcoded string found')
  - (415, 'Hardcoded string found')
  - (416, 'Hardcoded string found')
  - (417, 'Hardcoded string found')
  - (418, 'Hardcoded string found')
  - (419, 'Hardcoded string found')
  - (420, 'Hardcoded string found')
  - (421, 'Hardcoded string found')
  - (423, 'Hardcoded string found')
  - (424, 'Hardcoded string found')
  - (425, 'Hardcoded string found')
  - (427, 'Hardcoded string found')
  - (430, 'Hardcoded string found')
  - (433, 'Hardcoded string found')
  - (434, 'Hardcoded string found')
  - (435, 'Hardcoded string found')
  - (436, 'Hardcoded string found')
  - (437, 'Hardcoded string found')
  - (438, 'Hardcoded string found')
  - (446, 'Hardcoded string found')
  - (447, 'Hardcoded string found')
  - (448, 'Hardcoded string found')
  - (450, 'Hardcoded string found')
  - (451, 'Hardcoded string found')
  - (452, 'Hardcoded string found')
  - (453, 'Hardcoded string found')
  - (454, 'Hardcoded string found')
  - (455, 'Hardcoded string found')
  - (457, 'Hardcoded string found')
  - (458, 'Hardcoded string found')
  - (459, 'Hardcoded string found')
  - (462, 'Hardcoded string found')
  - (465, 'Hardcoded string found')
  - (469, 'Hardcoded string found')
  - (470, 'Hardcoded string found')
  - (471, 'Hardcoded string found')
Issues in src/components/BitcoinTracker.js:
  - (2, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
Issues in src/components/Footer.js:
  - (2, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
