### ISSUE TITLE
Issue-Add Coin Data Fetch Request with Jest Mock

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/coinage#73]
Automated Review Comments
Issues in src/__mocks__/requestData.js:
  - (13, 'Hardcoded string found')
Issues in src/__tests__/BitcoinTracker.test.js:
  - (1, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
Issues in src/components/BitcoinTracker.js:
  - (8, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
